spring:
  application:
    name: usuario-service
  profiles:
    active: dev
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8088


# WebClient Config
services:
  telefonos:
    url: http://localhost:8086
  direcciones:
    url: http://localhost:8087